name: Build and Deploy to `build` Branch

on:
  push:
    branches:
      - main  # Runs every time you push to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Adjust based on your project
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Deploy to `build` branch
        run: |
          # Configure Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Ensure the build branch exists
          git fetch origin build || true
          if git show-ref --verify --quiet refs/heads/build; then
            git checkout build
            git merge --ff-only main || true
          else
            git checkout -b build
          fi

          # Force add dist/ even if in .gitignore
          git add -f dist/

          # Commit and push changes
          git commit -m "Build: Update dist files" || true
          git push origin build
