name: Deploy to dist branch

on:
  push:
    branches:
      - main  # Trigger this when there's a push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the main branch (to get the latest changes)
      - name: Checkout main branch
        uses: actions/checkout@v3

      # Checkout the dist branch to push the built files
      - name: Checkout dist branch
        run: git fetch origin dist:dist && git checkout dist

      # Set up Node.js and install dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # Build the project to generate dist files
      - name: Build project
        run: npm run build

      # Add dist directory to git
      - name: Add dist files
        run: |
          git add dist/
          git commit -m "Deploy new dist files"

      # Push changes to the dist branch
      - name: Push dist branch
        run: git push origin dist --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
